name: 'Unity Build'

on: [push]

jobs:
  build:
    name: build project
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - run: '& "C:\Program Files\PowerShell\7\pwsh.exe"'
      - run: F:\__INDIELINY__\CI\BuildRun.ps1

      - uses: actions/upload-artifact@v4
        with:
          name: Build
          path:  F:\__INDIELINY__\CI\__BUILD_OUTPUT__\.
